basic_info = {
    type='hero',
    card_info={
        name='超科学爆爆博士',
        style='charge',
        lp=32,
        zone_guid='12b623',
        skill_num=3,
        skill={
            draw=2,
            keyword={
                type='or',
                resource={
                    fire=-3,
                },
                charge_3={
                    resource={
                        power=3,
                        life=3,
                        type='or',
                    }
                }
            }
        }
    },
}
