#+STARTUP: INDENT NUM

* Introduction to Dealing with Financial Stress
Money is a very common source of stress. Some simple techniques can help you start to deal with this stress.

Stress over money has been with us for as long as there has been money, so if you are overwhelmed or feeling the effects of stress, you are not alone, and you never have been alone.

Some people think that just having a million dollars would solve all their problems and their stress, but the truth is, it probably wouldn’t, and it might bring even more stress—like aggressive relatives you haven’t seen in 30 years!

Sometimes we are suffering from financial stress without even knowing it. So an important step is to identify how it is affecting you. Beyond that, there is much you can do to relieve the symptoms and start attacking the problem itself. This tutorial is a very basic set of ideas and reminders to help you with that.


* How Financial Stress Can Affect Your Health
No one is immune to financial stress. If unmanaged, stress can lead to damaging conditions like sleep disorders, anxiety, and depression. The good news is that there are ways to manage stress caused by your finances.

THINGS TO KNOW
The first step toward managing your financial stress is becoming aware of how it affects your life.
The first step toward managing your financial stress is becoming aware of how it affects your life. Read below to see if stress is affecting your life in the following ways:

You are taking part in unhealthy ways of coping, like smoking, excessive drinking, overeating, or using drugs
Some people try to manage stress by doing harmful activities that feel exciting or fun, but they are unhealthy and actually lead to more stress.

You aren’t using money for important items like food and healthcare
When caught in a budget crunch, some people sacrifice necessities in order to pay for nonnecessities. This can lead to more stress and a decrease in physical well-being.

You have unhealthy thought processes
When times are tough, it’s easy to get negative. However, negative thoughts can have harmful emotional and physical effects, and cause depression or anxiety.

You are losing sleep because of stress
Sometimes stress can cause our sleep patterns to shift for the worse. If stress is affecting your sleep, it can cause moodiness, impairment of immune and cognitive functioning, and greater levels of stress.

Now that you are aware of common activities that lead to increased stress levels, you can find out what to do to avoid them. You can feel better about finances by keeping a budget, learning what to do to get out of debt, and also by learning stress-reducing techniques that will help you relieve not only financial stress, but the overall levels of stress in your life. Some helpful stress-relieving techniques you may want to explore are:

exercise
taking a yoga class
meditation
breathing techniques
massage
taking a walk
progressive muscle relaxation
listening to relaxing music


* Reduce Your Anxiety over an Uncertain Economy
In a tumultuous economic climate, it’s easy to feel anxious or nervous. However, you can make a choice to let the stress overpower your life, or you can manage the stress you feel and aim to live as happily and healthfully as you can. If your stress over the economy is running rampant, here are some tips to better handle your feelings:

THINGS TO KNOW
You can make a choice to let the stress overpower your life, or you can manage the stress.
Think about what you can change and what you can’t change
Do your part to change your financial situation for the better, but if there are factors you can’t control, don’t let them get you down. Do as much as you can for you and your family’s finances, and then let go of what you can’t control.

Don’t dwell on possible circumstances
For instance, if you think you might lose your job, don’t let that fear overtake you. If you do, you might start performing poorly in your present job or cause yourself stress-related illness. Instead, give your best in your current situation and know that doing the best you can is the best thing you can do.

Know when to put down the newspaper or turn off the TV
It’s great to stay educated on financial happenings, but know that the media can often paint a dreadful, fear-ridden picture. Give yourself a certain amount of time each day or week to educate yourself on financial topics, and then switch to a more calming activity.

Stay focused on the good
Think about what you do have and what you will have, no matter what: family, close friends, and the things you have that money can’t buy. When you consider this, it’s easy to see that it’s better and wiser to focus on the best parts of your life rather than the life of an everchanging economy.

Practice being grateful and explore relaxation techniques
Take time each morning or evening to think about what you are grateful for. This could be having food to eat, a place to live, loved ones, or anything else that makes you feel good. Also, take time each day to relax. You can take a yoga class, practice meditation at home, take a hot bath, or take a walk outside.


* How to Stop Arguing with Your Partner over Finances
It’s common for couples to fight about finances. But battling with your partner won’t help your finances or the well-being of your relationship. Instead, find out how you and your partner can work together for financial freedom:

THINGS TO KNOW
Know both your view of money and your partner’s.
Before the arguments have a chance to start …
Know both your view of money and your partner’s. If the two of you understand one another’s financial outlooks, you’ll be better able to know where the other is coming from and you’ll be less likely to fight. In addition, when you get everything out on the table, you can compromise and make decisions that help both of you get what you need.
Budget and plan together. Make sure both of you know the amount of money that’s being made, where it’s going, what debt you have, and other key financial points. Your family will operate better if two people are working with one another for common goals.
Look for answers
Aim for solutions, rather than contributing to problems. In arguments, we all want to vent our frustrations. But what’s more important is discussing problems with a focus on finding solutions. When you and your partner discuss financial issues, keeping your eyes on finding solutions will reduce problems and stress.
If things get too heated …
If you feel an argument flaring up over finances, breathe and stay calm. It’s important to discuss all matters with an open and calm mind, especially when you’re talking about money. Therefore, when you discuss money, put on some calming music, hold hands, use calming breathing techniques, or try some other way to help the two of you stay tranquil while you discuss what’s important.
Feel free to take breaks while you talk. If things get too heated, take a walk together and chat about something else. Or, take a walk alone so each person can clear his or her head. You can even consider watching a funny movie to lighten the mood. Whatever way you choose to spend your break, when you rejoin to discuss, you’ll be better able to talk calmly and rationally about the important topics at hand.
If all else fails …
If you’ve tried all of the above tips, and things still aren’t getting better, consider seeing a financial advisor. If your marriage is rocky because of finance-related fights, it may be wise to consider seeing a marriage counselor. Don’t be shy to ask for help when it’s needed.

* Reducing Financial Stress: Replacing Unhealthy Coping Behaviors
Unhealthy Ways of Dealing with Stress
When under financial stress, people may indulge in unhealthy coping behaviors. As you first start engaging in these behaviors, they may feel like stress-reducers, but in the end, they add more stress to your life. Common unhealthy coping behaviors include:

THINGS TO KNOW
Unhealthy coping behaviors can lead to both physical and mental problems.
overeating
drinking
drug use
caffeine consumption
smoking
gambling
Many of these unhealthy coping behaviors can lead to both physical and mental problems. Overeating or smoking, for example, can cause a slew of potential health complications. Excessive drinking is not only physically harmful, but it can lead to depression and cause strain in relationships. In addition, instead of helping you out of debt or other financial problems, these types of behaviors cost you money along with your physical and mental wellbeing.

Healthy Ways of Dealing with Stress
There are other coping behaviors that not only soothe your financial stress, but lead to a more happy and healthy life. Instead of partaking in coping behaviors that cause more stress, try these behaviors that are proven to reduce stress:

exercising
eating well
listening to calming music
taking a walk outside
journaling
taking a yoga class
using meditation or breathing techniques
Document feelings and solutions
Keeping note of what you feel during stressful times can help you get your emotions out in a positive way. Writing down what you are going through and what you feel can help create solutions for your money problems.

When to Get Help
If you are having problems coping with stress, or cannot stop unhealthy ways of coping, talk to your doctor about finding help. Your employee assistance program or your employer may also provide referrals to support groups for stress and other resources to help you find healthy ways to reduce stress in your life.

* Summary of Dealing with Financial Stress
Having a Financial Plan Can Reduce Financial Stress
When people want to get serious about putting their financial lives on track, they create financial action plans. So, too, do they make action plans for reducing stress.

The value of having a plan is that you can see where you need to go and what you need to do. It keeps you on track and promises that, if you do what it says and nothing unexpected happens to it, you will get where you need to go. Without such a plan, you probably won’t; you probably wouldn’t even know the end result if and when you saw it.

At the very least, just the fact of having a plan can reduce stress. But you want to go further than that. A plan can:

Show you how and where and why you are experiencing stress
Identify triggers for stress
Discipline your spending
Help you identify which stress relievers work best for you
Set a schedule for practicing stress relief exercises
Show you solutions that you hadn’t thought of before
Creating a stress action plan can be as simple as setting some goals and some means of achieving them. Let’s look at some examples:

Practical Ideas I Can Start with Today
Identify broad areas of my financial life that cause me stress.
Identify specific stress triggers that lead me to engage in unhealthy behaviors.
Identify my unhealthy behaviors that I use to deal with stress.
Identify and try out healthy reactions to my triggers.
