#+STARTUP: INDENT NUM

* 介绍: 处理财务压力
钱是一种非常常见的压力来源, 有一些简单的技巧来帮助你应对这种压力.
只要有钱, 压力就一直伴随着我们. 如果你不知所措, 感受到了压力的影响, 你并不孤单, 也从未孤单.
有些人认为成为百万富翁就可以解决所有问题和他们的压力, 但真相可能并非如此, 这可能会带来更大的压力.
某时我们在不知不觉中承受着金融压力, 重要的一步就是识别它是如何影响你的. 除此之外, 你可以做很多事情来缓解症状甚至处理问题本身.

* 财务压力如何影响你的健康
没人能够免疫财务压力, 如果不加以管理, 压力将会导致失眠障碍, 焦虑, 抑郁. 好消息是有多种办法来管理财务造成的压力.

管理财务压力的第一步是认识到它是如何影响你的生活的:
- 你在参与不健康的应对方式. 比如抽烟, 酗酒, 暴食, 吸毒. 有人尝试用有伤害性但是带来兴奋感的活动来管理压力, 事实证明这将带来更多压力.
- 你不将钱用到重要的事情上. 比如饮食和医疗, 当陷入到预算紧张的情况时, 有人会牺牲不必要的支出. 这将会导致更大的压力, 损害身体状况.
- 你有不健康的思维过程, 当时局艰难, 很容易消极, 消极思想会伤害你的情绪和身体, 导致抑郁和焦虑.
- 你因为压力而失眠, 压力会导致我们的睡眠模式变得更糟, 如果压力影响了你的睡眠, 将导致情绪低落, 压力提高.

一些常见的缓解压力的方式:
- 锻炼
- 参加瑜伽课程
- 冥想
- 呼吸技巧
- 散步
- 按摩
- 肌肉放松
- 听轻松舒缓的音乐

* 减少对不确定经济的焦虑
在动荡的经济环境中, 非常容易感到紧张或焦虑, 然而, 你可以选择让压力压倒你的生活, 或者管理压力让自己尽可能获得快乐健康.

1. 思考什么是你可以控制的, 什么是你无法控制的
   尽自己的力量让财务情况变好, 如果有你无法控制的因素, 放下他们
2. 不要纠结于可能的情况
   例如, 你认为自己可能会失业, 请不要让这种恐惧笼罩你, 请在当前情况下尽力而为
3. 知道何时放下报纸, 关闭电视
   保持对金融事件了解是很哈的, 但是媒体经常夸张事实, 所以要定时的了解这些消息
4. 专注于好的事情
   想想你做了什么, 你拥有什么, 那些用钱买不到的东西. 与考虑不断变化的经济相比, 这会更为明智
5. 练习感恩并探索放松技巧
   每早晚思考想想感恩的是什么. 每天抽空放松一下, 比如散步, 瑜伽.

* 停止和伴侣在财务上的争吵
和伴侣在财务问题上吵架是很常见的, 但是这对你们的关系和财务情况都不会有帮助.

1. 在争论开始之前, 了解双方对金钱的看法是很重要的. 如果两人都了解对方的财务看法, 那么你们不太可能发生争论.
2. 一起计划和预算是很重要的, 让双方都了解你们的收支, 债务, 财务关键点. 如果两人为了共同点目标而奋斗, 那么关系会更好
3. 寻找答案而不是助长问题, 不要发泄挫败感
4. 如果讨论变得过于紧张严肃, 深呼吸保持镇定, 在开放和冷静中讨论所有事务是非常重要的. 两个人可以散步, 看视频, 讨论其他话题来缓和气氛
5. 如果协商失败, 可以寻求专业人员的帮助, 这并不丢人

* 减少财务压力, 不健康的应对行为
** 不健康的应对压力的方式
当处于经济压力之下时, 人们可能用不健康的行为来应对压力. 当你第一次开始从事时, 你可能会觉得压力有所减轻, 但到最后只会增加更多压力.

不健康的应对行为可能导致身体和精神两方面的问题, 常见的不健康方式有:
- 暴饮暴食
- 酗酒
- 嗑药
- 咖啡因
- 吸烟
- 赌博

** 健康的应对压力方式
有部分行为被证明可以有效减小压力, 且对身体健康有益. 健康的应对压力行为有:
- 锻炼
- 健康饮食
- 听平静的音乐
- 散步
- 旅行
- 参加瑜伽课
- 使用冥想或者呼吸技术

** 记录面对压力的感受和解决方式
记录下面对压力的感受可以帮助你积极的释放情绪, 写下经历的事情可以帮助你找到解决金钱问题的方案.

** 什么时候寻求帮助
如果你面对压力时有问题, 或者不能停止使用不健康的方式应对, 咨询你的医生来寻求帮助.

* 总结
** 拥有财务计划可以降低财务压力
当人们想要认真记录生活中的财务时, 它们创建了财务活动计划, 这个计划告诉你应该怎么做, 你将获得什么. 如果没有这份计划显然你将对未来一无所知, 这也是压力的来源.
计划的具体好处有:
- 展示面对压力的时间, 地点, 原因
- 确定压力的诱因
- 约束你的花费
- 帮助你确定哪种压力缓解方案对你最有效
- 创建减压练习计划
- 向你展示你以前从未想过的解决方案
** 压力行动计划举例
- 今天可以开始的想法
- 确定财务生活中产生压力的广泛区域
- 确定导致自己从事不健康行为的特定压力触发因素
- 确定我的应对压力的不健康行为
