#+STARTUP: overview indent

* 什么是spine动画
spine动画是指把角色的各部分身体部件图片绑定到一根根互相作用连接的 *骨头* 上, 通过
控制这些骨骼的位置, 旋转方向和放大缩小而生成的动画.

* spine动画的优势
** 帧动画
首先明确一下传统动画的是实现方式帧动画的概念, 所谓的帧动画, 即是每一帧都是某个场
景的快照, 动画的流畅度和平滑度都取决于帧数的多少.

** 主要优势
- 更少的美术资源 :: spine动画的资源是由一块块角色部件图像构成, 而帧动画的资源是
  每一帧独立的图像构成
- 更小的体积 :: 由于使用的图像很少, 并且数据文件的体积也非常小, 所以体积远远小于
  帧动画
- 更好的流畅性 :: spine动画使用差值算法计算中间帧, 能让动画总是保持流畅
- 更换图片 :: 可以通过复用骨骼数据来修改资源图像, 实现一套骨骼绑定多个角色形象
- 动画混合 :: 不同spine动画可以结合到一起, 实现一个角色同时使用多套动作
- 程序动画 :: 可以通过程序代码控制骨骼, 实现种种特殊效果

* spine动画的构成
** 逻辑结构
*** 骨架
可设置动画的角色或对象, 它包含了 *骨骼*, *插槽*, *附件*, *动画*
*** 骨骼
类似于cocos里的一个Node对象, 包含旋转, 平移, 缩放, 裁剪等变换数据, 并且可以拥有
若干个子骨骼. 每个子骨骼递归的拥有子骨骼, 但只能有一个根骨骼. 父骨骼一经变换, 其
子骨骼也会受影响
*** 插槽
插槽是骨骼的子集, 骨骼是插槽的容器. 它是一个概念性的对象, 标记了骨骼上的一个特殊
位置, 本身只拥有颜色属性. 插槽的主要作用在于附加附件, 灵活的决定绘制顺序
*** 附件
附加到骨骼上的东西, 比如图片, 比如碰撞框. 但附件不会直接附加到骨骼上, 而是附加到
插槽中. 一个插槽可以同时拥有多个附件, 但只能有一个可见
*** 皮肤
简单来说就是一组附件的集合, 通过切换皮肤可以轻易地实现spine动画的复用
*** 动画
基于时间轴模式的骨骼变换列表
** 物理结构
*** 数据文件
一组包含了骨骼动画在各个帧变换数据的数据文件, 一般为.skel结尾的二进制文件或者
以.json结尾的json文件, json文件可读性更好, 更容易修改但体积更大.
数据结构: [[http://zh.esotericsoftware.com/spine-json-format][spine动画.json数据结构]], [[http://zh.esotericsoftware.com/spine-binary-format][spine动画.skel数据结构]]
*** 资源文件
为了使资源体积更小, 一般资源文件不是由一张张图片构成的, 而是把若干图片合成为一个
大的图片, 称之为合图, 合图一般由两部分构成
- png文件 :: 无损的图像数据文件, 所有的图像资源紧密的压缩在图像中
- altas文件 :: 记录了每个分图在png文件中的位置, 通过这个文件可以将合图解压缩
  数据结构: [[http://zh.esotericsoftware.com/spine-atlas-format][spine动画.altas数据结构]]
  
* spine动画的在代码中的应用
在两个最重要的接口setAnimation(立即播放一个动画)和addAnimation(添加一个动画到播放
列表)中, 我们会看到一个特殊的参数track, track的作用是为了让动画可以混合. 可以让角
色在同一时间播放多个动画. track更高的动画会覆盖track较低的动画.
* spine制作中的高级概念
** FK和IK
FK是正向运动学, IK是反向运动学. fk是一种自顶向下的思路, 即如果我要运动手, 我要
先运动大臂, 然后运动小臂, 最后在调整手的位置. 而ik相反, 直接设置手的位置, 自动
计算出大臂和小臂的位置
** 网格
允许你在矩形边界内自定义多边形, 这将提高最终纹理贴图集的空间使用率, 这一功能是自
由变形和蒙皮的基础
*** 自由变形
允许你移动网格的点来是图片变形, 可以实现网格的拉伸, 挤压, 弯曲, 反弹等一系列矩形
图片无法实现的功能
*** 蒙皮
蒙皮允许将网格中指定的点附加给指定骨骼, 然后附加点将随着骨骼移动. 网格则随之自动
发生变形. 可以用骨骼动作控制角色的图片进行弯曲变形

* spine相关工具
- [[http://zh.esotericsoftware.com/spine-download][spine编辑器]] :: 制作spine动画的工具, 导出spine动画
- [[http://zh.esotericsoftware.com/spine-skeleton-viewer][skeleton viewer]] :: 骨骼浏览器, 快速查看spine动画骨骼数据
- [[https://github.com/EsotericSoftware/spine-superspineboy][super spineboy]] :: 一个使用spine动画制作的游戏, 其源代码展示了如何使用spine动画

