MESSAGE(STATUS "Assimp is used")
ADD_DEFINITIONS(-D__USING_ASSIMP__)

# 包含头文件路径和链接库
INCLUDE_DIRECTORIES(${MYDEPS}/assimp/include)

SET(ASSIMP_LIB assimp)

SET(LIB_ASSIMP_PATH ${MYDEPS}/assimp/lib/${MYPLATFORM})
MESSAGE(${LIB_ASSIMP_PATH})
seek_deps_library(${LIBS_PATH} ${LIB_ASSIMP_PATH} ${ASSIMP_LIB})

SET(LINK_ASSIMP_LIBS ${ASSIMP_LIB})
