MESSAGE(STATUS "gtest is used")
ADD_DEFINITIONS(-D__USING_GTEST__)

SET(GTEST_LIB gtest)

SET(LIB_GTEST_PATH ${MYDEPS}/gtest/lib/${MYPLATFORM}/${CMAKE_BUILD_TYPE})
seek_deps_library(${LIBS_PATH} ${LIB_GTEST_PATH} ${GTEST_LIB})

# 包含头文件路径和链接库
INCLUDE_DIRECTORIES(${MYDEPS}/gtest/include)
SET(LINK_GTEST_LIBS ${GTEST_LIB})
