MESSAGE(STATUS "easyengine is used")
ADD_DEFINITIONS(-D__USING_EASYENGINE__)

# 包含头文件路径和链接库
INCLUDE_DIRECTORIES(${MYDEPS}/easyengine/include)

SET(EASYENGINE_LIB easy_engine)

SET(LIB_EASYENGINE_PATH ${MYDEPS}/easyengine/lib/${MYPLATFORM})
MESSAGE(${LIB_EASYENGINE_PATH})
seek_deps_library(${LIBS_PATH} ${LIB_EASYENGINE_PATH} ${EASYENGINE_LIB})

SET(LINK_EASYENGINE_LIBS ${EASYENGINE_LIB})

