MESSAGE(STATUS "stb_image is used")
ADD_DEFINITIONS(-D__USING_STB_IMAGE__)

# 包含头文件路径和链接库
INCLUDE_DIRECTORIES(${MYDEPS}/stbimage/include)

SET(STB_IMAGE_LIB stb_image)

SET(LIB_STB_IMAGE_PATH ${MYDEPS}/stbimage/lib/${MYPLATFORM})
MESSAGE(${LIB_STB_IMAGE_PATH})
seek_deps_library(${LIBS_PATH} ${LIB_STB_IMAGE_PATH} ${STB_IMAGE_LIB})

SET(LINK_STB_IMAGE_LIBS ${STB_IMAGE_LIB})
