#+STARTUP: INDENT NUM

* 项目管理
1. 使用unity hub进行项目的创建, 管理, 删除
2. unity hub可以分别管理不同版本引擎创建的项目
3. unity hub能够以多种形式创建项目, 比如2d, 3d. 这些设置影响编辑器内某些设置, 比
   如相机的透视, 资源的导入形式等等

* 资源导入
** 常见的导入形式
   - 在项目窗口, 右键点击->导入新资源
   - 在项目窗口, 右键点击->导入包->自定义包(这个包一般是由unity导出的)
** 资源管理
*** 目录管理
   在Assets目录下, 包含了游戏全部需要的资源, 这个目录可以像文件浏览器中那样随意创
   建文件夹, 移动, 删除. 通常我们会创建以下几个目录:
   - Scenes: 游戏自动创建, 用来保存场景
   - Scripts: 保存游戏脚本
   - Prefabs: 保存预制体
*** 场景管理
   - 通过点击顶部菜单File->New Scene来创建新的场景, File->Save来保存它
   - 通过在Scenes目录内找到Scene, 点击del来删除场景
   - 通过在Scenes目录内找到Scene, 双击来打开新场景

* 界面
** 布局
右上角的Layout可以调整整个编辑器的布局, 下面的说明均以Default布局为基础进行说明
** 菜单栏
在编辑器的最上方是菜单栏, 可以使用大部分经典的软件命令, 比如编辑编辑器配置, 打开
保存文件等等
** 工具栏
位于菜单栏下面的是工具栏, 可以访问移动, 旋转, 缩放工具; 中间的三个按钮用来控制
场景的播放. 使我们可以不打开游戏就可以在编辑器内预览游戏的实际表现; 最右边代表着
unity的服务, 比如云构建
** 层次结构窗口
位于编辑器左方, Hierarchy窗口显示着场景内部所有的游戏对象, 以及它们的父子关系
** 场景/游戏/商店视图
位于编辑器的中央, 包含了三个子窗口:
*** 场景
我们操纵游戏对象, 创建关卡的窗口, 点击里面的对象会在层次结构窗口高亮显示,
并且会打开游戏对象的检视窗口, 用以浏览对象的属性
*** 游戏
主摄像机在场景内部看到的全部内容, 点击工具栏里的播放按钮会自动调到这个页面. 通过
在菜单栏里Edit->Preferences->Colors->playmode tint, 可以在进入播放模式时变色,
用来提醒你进入了播放模式(因为在播放模式下对对象的修改是不会保存的)
*** 商店
可以查看在Assets Store中可以购买和自己拥有的不同资源
** 检视窗口
上下文相关的窗口, 随着选中的对象不同而表现不同的属性. 代表着选中对象的可编辑参数
** 项目/控制台窗口
*** 项目
可以访问项目的源资源, 在这里如果对源资源进行修改会影响到所有使用到这个资源的场景
*** 控制台
显示脚本中的警告, 错误, 调试日志等

* 场景导航
** 场景移动
场景导航代表着我们在场景视图中移动的方式:
- alt+鼠标左键: 环绕3d空间中特定点
- alt+鼠标中键: 拖动, 平移
- alt+鼠标右键 或 滚轮: 放大, 缩小
- 鼠标右键: 以自身为轴环顾周围
- w/s/a/d+鼠标右键: 世界飞行模式浏览
- f: 快速定位到选中对象
** 对象控制
选中对象之后, 工具栏上六个按钮以及两个选项卡均为可用状态.
*** 选项卡
- Center/Pivot: 控制对象时, 以对象中心为控制点还是以对象的锚点作为控制点
- Global/Local: 控制对象时, 使用全局坐标系还是局部坐标系
*** hand tool(热键:q)
拖动场景, 对象不会变化
*** move tool(热键:w)
移动工具, 有两种使用方式:
- 点击x/y/z任意轴并拖动, 可以在这个轴上进行平移
- 点击中心立方体的一面并拖动, 可以在两轴形成的面上移动
*** rotate tool(热键:e)
旋转工具, 以三个轴来旋转对象(俯仰角[Pitch], 偏航角(Yaw), 滚转角[Roll])
*** scale tool(热键:r)
缩放工具, 有两种使用方式:
- 点击轴末端的小立方体, 在这个轴上进行缩放
- 点击中心的立方体, 在三个轴上同时缩放
*** rect tool(热键:t)
2d资源使用, 3d一般不会使用这个工具
*** move, rotate, scale tool(热键:y)
可以同时进行移动,旋转和缩放


* 对象
unity的每个对象都被视为游戏对象, 它们基本上只是空容器, 通过添加组件来改变其行为.
